# -*- coding: utf-8 -*-
"""파이썬으로서울시코로나19웹크롤링.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12glyRf3uQUDOPa8jJw1R-qnC4y9_n2GE
"""

import pandas as pd

url = "https://www.seoul.go.kr/coronaV/coronaStatus.do?menu_code=01"
url

pd.read_html(url)

table = pd.read_html(url)
len(table)
# len 불러온 개수

table[0]

table[0].transpose()
#table[0].T
#행과 열 바꾸기
#지금은 열로 바꾸기

table[4]

df = table[4]
df.shape
#행렬표시

df.head()

df.loc[0]
#1번 데이터만 가져옴

df.loc[0,'확진일']

last_day = df.loc[0,'확진일']
last_day

last_day = df.loc[0,'확진일']
last_day = last_day.replace('.', '_')
last_day
#.을 _(언더바)로 변경

file_name = f'seoul-covid19_{last_day}.csv'
file_name
#파일명 만들기

df.to_csv(file_name, index=False)
#index=False(index는 저장하지 않기)

df.to_csv(file_name)
#파일로 저장

df

pd.read_csv(file_name)
#저장한 파일 불러오기

df.to_csv(file_name, index=False, encoding='cp949')
#엑셀에서 열어볼 수 있게 저장

pd.read_csv(file_name, encoding='cp949')
#엑셀로 저장한 파일 불러오기

